import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'

import Date from '../../components/Date'

import { getSortedPostsData } from '../../lib/posts'

export default function Blog({ filtro }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Felipe Ferreira</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Component.svg" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Blog page
        </h1>

        <p className={styles.description}>
          Posts sobre javascript 
        </p>

        <Link href={"/blog"}>
          <button>Todos os posts</button>        
        </Link>

        <div className={styles.grid}>
          {filtro.map((post, index) => (
          <Link href={'/blog/' + post.slug} passHref key={index}>
            <div className={styles.card}>
              <div className={styles.cardText}>
                <h2>{post.title}</h2>
                  <p>
                    <Date dateString={post.date} />
                  </p>
                  <p>{post.tags}</p>
                  <p>{post.description}</p>
              </div>
              <div>
                <Image
                  src={post.thumbnailUrl}
                  alt="thumbnail"
                  width={1000}
                  height={1000}
                  objectFit="cover"
                />
              </div>
            </div>
          </Link>
        ))}
        </div> 
      </main>

      <footer className={styles.footer}>
        Blog desenvolvido por Felipe Ferreira
      </footer>
    </div>
  )
}

export async function getStaticProps() {
  const allPostsData = getSortedPostsData()
  const filtro = allPostsData.filter(i => i.tags === 'javascript')
  return {
    props: {
      filtro
    }
  }
}
